Lyric Censoring [YARG-22]
YARC-Official/YARG.Core pull request #106
Opened 2023-11-02 11:08 UTC by BurAndBY

Censoring lyrics using `lyric_explicit` prefix. 
Solution to [YARG-22](https://yarg.youtrack.cloud/issue/YARG-22/Censored-vocals).

2023-11-02 11:28 UTC, RileyTheFox commented on YARG.Core/MoonscraperChartParser/TextEventDefinitions.cs
> +        E_LYRIC_PREFIX = "lyric_explicit",
Would suggest naming this `EXPLICIT_LYRIC_PREFIX` or `LYRIC_EXPLICIT_PREFIX` just for slightly better clarity

2023-11-02 11:28 UTC, RileyTheFox commented on YARG.Core/Chart/Loaders/MoonSong/MoonSongLoader.Vocals.cs
> +        					lyrics.Add(new(new string('-', lyric.ToString().Length) + " ", time, moonEvent.tick));
Should we use `*` characters to notate censored lyrics as is pretty standard for censoring?

Should we be removing the lyric entirely if it's censored as I presume the point is to not sing it at all? I'm not a vocals player so additional input about this would be useful

2023-11-02 11:30 UTC, BurAndBY commented on YARG.Core/Chart/Loaders/MoonSong/MoonSongLoader.Vocals.cs
> +        					lyrics.Add(new(new string('-', lyric.ToString().Length) + " ", time, moonEvent.tick));
The asterisk character is not supported in the current lyrics font (not being displayed)

2023-11-02 11:31 UTC, BurAndBY commented on YARG.Core/MoonscraperChartParser/TextEventDefinitions.cs
> +        E_LYRIC_PREFIX = "lyric_explicit",
Fixed.

2023-11-02 21:07 UTC, EliteAsian123 commented on YARG.Core/Chart/Loaders/MoonSong/MoonSongLoader.Vocals.cs
> +        					lyrics.Add(new(new string('-', lyric.ToString().Length) + " ", time, moonEvent.tick));
The asterisk character *is* supported in the font, it's just not being displayed, as it's [a special character that denotes non-pitched notes](https://github.com/TheNathannator/GuitarGame_ChartFormats/blob/main/doc/FileFormats/.mid/Standard/Vocals.md#lyrics-markup). Like what Riley said in the Discord, it's probably a better idea to add a new bool field to `VocalNote` or create a flags field like in [`GuitarNote`](https://github.com/YARC-Official/YARG.Core/blob/ae4a4e1ecc2828dc902f7df7d5574d231373cbb3/YARG.Core/Chart/Notes/GuitarNote.cs#L9). This flag can then be used on the YARG side to censor out a lyric when displaying it in `VocalLyricElement` and in the `LyricBar`.

2023-11-02 21:08 UTC, EliteAsian123 requested changes
Thanks for the PR!

Like what Riley said in the Discord, it's probably a better idea to add a new bool field to `VocalNote` or create a flags field like in [`GuitarNote`](https://github.com/YARC-Official/YARG.Core/blob/ae4a4e1ecc2828dc902f7df7d5574d231373cbb3/YARG.Core/Chart/Notes/GuitarNote.cs#L9). This flag can then be used on the YARG side to censor out a lyric when displaying it in `VocalLyricElement` and in the `LyricBar` (which will fix the asterisk problem).

2024-02-20 03:18 UTC, EliteAsian123 commented
Closing for now as this is stale. Please feel free to reopen a new PR if you ever decide to come back to this!

2024-02-20 03:18 UTC, closed without merging