Bass multiplier
YARC-Official/YARG.Core pull request #117
Opened 2023-11-27 04:22 UTC by grishhung

Super quick and dirty reimplementation of the bass multiplier. Needed to be reimplemented on the engine side before I could do other changes related to text notifications and bass groove.

2023-11-27 04:40 UTC, TheNathannator requested changes
Try to avoid "quick and dirty" if you can help it, that's kinda why we rewrote everything in the first place lol

2023-11-27 04:42 UTC, RileyTheFox requested changes

2023-11-27 04:42 UTC, RileyTheFox commented on YARG.Core/Engine/Guitar/GuitarEngine.cs
> +        private bool _isBass;
This should be a guitar engine parameter passed in from YARG

2023-11-27 04:42 UTC, RileyTheFox commented on YARG.Core/Chart/Tracks/InstrumentDifficulty.cs
> +        public bool IsBass()
Should be handled on the YARG side using the player's profile instrument. Having a function in here that is somewhat instrument specific violates its generic-ness.

2023-11-27 04:42 UTC, RileyTheFox commented on YARG.Core/Engine/Guitar/GuitarEngine.cs
> +                EngineStats.ScoreMultiplier = EngineStats.Combo switch
The _isBass class field should be removed and an engine parameter be opted for instead.

This if/else switch expression can be de-duplicated by doing something like the following:

```
var isBass = EngineParameters.IsBass;

EngineStats.ScoreMultiplier = EngineStats.Combo switch
{
    >= 50 => isBass ? 6 : 4,
    >= 40 => isBass ? 5 : 4,
    >= 30 => 4,
    >= 20 => 3,
    >= 10 => 2,
    _     => 1
};
```

2023-11-27 04:46 UTC, TheNathannator commented
lol, we're both on top of this right now

2024-01-14 18:25 UTC, EliteAsian123 commented
Closing as this was added in https://github.com/YARC-Official/YARG.Core/commit/8009190f38772a93c0d3dcd8ca31072847e76567

2024-01-14 18:25 UTC, closed without merging