Remove invalid phrase events from the chart to fix invalid song end time
YARC-Official/YARG.Core pull request #145
Opened 2024-02-09 20:03 UTC by jgoyvaerts

2024-02-09 23:49 UTC, TheNathannator requested changes

2024-02-09 23:49 UTC, TheNathannator commented on YARG.Core/Chart/Loaders/MoonSong/MoonSongLoader.Lyrics.cs
> +            var maxTick = _moonSong.Charts.Max(x => x.notes.LastOrDefault()?.tick ?? 0);
This needs to account for the lyric events as well, not just the notes. Probably better to use `events` here rather than `Charts`/`notes`.

Also would prefer explicitly accessing the list rather than using Linq, as Linq operates exclusively with `IEnumerable<T>` and will iterate over the entire list here to find the last item (assuming there isn't a specialization fast path for `List<T>` in the implementation).

```diff
- var maxTick = _moonSong.Charts.Max(x => x.notes.LastOrDefault()?.tick ?? 0);
+ int maxTick = _moonSong.events.Count > 0 ? _moonSong.events[^1] : 0;
```

2024-02-09 23:49 UTC, TheNathannator commented on YARG.Core/MoonscraperChartParser/IO/Chart/ChartReader.ProcessLists.cs
> +            var maxTick = chart.notes.LastOrDefault()?.tick ?? 0;
Same preference here:

```diff
- var maxTick = chart.notes.LastOrDefault()?.tick ?? 0;
+ int maxTick = chart.notes.Count > 0 ? chart.notes[^1] : 0;
```

2024-02-10 00:02 UTC, jgoyvaerts commented on YARG.Core/Chart/Loaders/MoonSong/MoonSongLoader.Lyrics.cs
> +            var maxTick = _moonSong.Charts.Max(x => x.notes.LastOrDefault()?.tick ?? 0);
Added the resolution and changed to events as requested.

No need to switch from Linq to direct: https://github.com/mono/corefx/blob/c4eeab9fc2faa0195a812e552cd73ee298d39386/src/System.Linq/src/System/Linq/Last.cs#L51

2024-02-10 00:02 UTC, jgoyvaerts commented on YARG.Core/MoonscraperChartParser/IO/Chart/ChartReader.ProcessLists.cs
> +            var maxTick = chart.notes.LastOrDefault()?.tick ?? 0;
No need to switch from Linq to direct: https://github.com/mono/corefx/blob/c4eeab9fc2faa0195a812e552cd73ee298d39386/src/System.Linq/src/System/Linq/Last.cs#L51

2024-02-10 00:03 UTC, TheNathannator commented on YARG.Core/MoonscraperChartParser/IO/Chart/ChartReader.ProcessLists.cs
> +            var maxTick = chart.notes.LastOrDefault()?.tick ?? 0;
We determined there is an optimization path for lists, so this is not much of a concern anymore:
https://github.com/mono/corefx/blob/5b4edb9b0a721aed60c9c8ddeed441bdd7451e42/src/System.Linq/src/System/Linq/Last.cs#L51

2024-02-10 00:07 UTC, TheNathannator approved these changes

2024-02-10 00:07 UTC, merged