Pro-keys Parsing
YARC-Official/YARG.Core pull request #163
Opened 2024-05-04 18:17 UTC by EliteAsian123

WIP

2024-05-10 02:26 UTC, TheNathannator requested changes
Some nitpicks, but otherwise looks good!

2024-05-10 02:26 UTC, TheNathannator commented on YARG.Core/Chart/Loaders/MoonSong/MoonSongLoader.ProKeys.cs
> +            }
Do we need to mark extended sustains and disjoint chords in Pro Keys? Mechanically, everything is treated as an individual note, and you can hit notes in chords independently from each other.

2024-05-10 02:26 UTC, TheNathannator commented on YARG.Core/Chart/SongChart.cs
> +            totalStartTime = Math.Min(ProKeys.GetStartTime(), totalStartTime);
```suggestion
            totalStartTime = Math.Min(TrackMin(ProKeys), totalStartTime);
```

2024-05-10 02:26 UTC, TheNathannator commented on YARG.Core/Chart/SongChart.cs
> +            totalEndTime = Math.Max(ProKeys.GetEndTime(), totalEndTime);
```suggestion
            totalEndTime = Math.Max(TrackMax(ProKeys), totalEndTime);
```

2024-05-10 02:26 UTC, TheNathannator commented on YARG.Core/Chart/SongChart.cs
> +            totalFirstTick = Math.Min(ProKeys.GetFirstTick(), totalFirstTick);
```suggestion
            totalFirstTick = Math.Min(TrackMin(ProKeys), totalFirstTick);
```

2024-05-10 02:26 UTC, TheNathannator commented on YARG.Core/Chart/SongChart.cs
> +            totalLastTick = Math.Max(ProKeys.GetLastTick(), totalLastTick);
```suggestion
            totalLastTick = Math.Max(TrackMax(ProKeys), totalLastTick);
```

2024-05-10 02:26 UTC, TheNathannator commented on YARG.Core/MoonscraperChartParser/IO/Midi/MidReader.ProcessLists.cs
> +            soloNote = MidIOHelper.SOLO_NOTE,
Pro Keys uses note 115 for marking solos, not note 103.

2024-05-10 02:26 UTC, TheNathannator commented on YARG.Core/MoonscraperChartParser/IO/Midi/MidReader.ProcessLists.cs
> +            versusPhrases = true,
This should technically be false, the versus modes were removed in RB3 and Pro Keys does not contain them.

2024-05-10 17:23 UTC, EliteAsian123 commented on YARG.Core/Chart/SongChart.cs
> +            totalStartTime = Math.Min(ProKeys.GetStartTime(), totalStartTime);
`TrackMin` takes in an enumerable of instrument tracks, so I just used its logic on the single pro-keys track.

2024-05-10 17:27 UTC, EliteAsian123 commented on YARG.Core/MoonscraperChartParser/IO/Midi/MidReader.ProcessLists.cs
> +            versusPhrases = true,
Fixed

2024-05-10 17:27 UTC, EliteAsian123 commented on YARG.Core/MoonscraperChartParser/IO/Midi/MidReader.ProcessLists.cs
> +            soloNote = MidIOHelper.SOLO_NOTE,
Fixed

2024-05-10 17:34 UTC, EliteAsian123 commented on YARG.Core/Chart/Loaders/MoonSong/MoonSongLoader.ProKeys.cs
> +            }
Good point. I just removed those flags entirely.

2024-05-11 20:20 UTC, merged

2024-05-11 20:22 UTC, TheNathannator commented on YARG.Core/Chart/SongChart.cs
> +            totalStartTime = Math.Min(ProKeys.GetStartTime(), totalStartTime);
Ah right, seems I missed it was using the enumerable helpers and not the individual tracks lol