YARG.Core changes for WaitCountdown support
YARC-Official/YARG.Core pull request #170
Opened 2024-05-14 16:06 UTC by sunset-cf

Additions to the Guitar, Drums, and Vocals engines to support countdowns during long stretches of no notes

2024-05-14 20:48 UTC, RileyTheFox requested changes
Requesting changes mostly based on some formatting mistakes but the other comments are there more for discussion rather than necessary changes.

Got quite a lot of engine changes planned very soon which would interfere with how this works slightly so want to discuss the implementations more.

2024-05-14 20:48 UTC, RileyTheFox commented on YARG.Core/Engine/BaseEngine.Generic.cs
> +                        // Countdown displays when the next note is farther MIN_COUNTDOWN_MEASURES
I think the system would work better if it required a minimum amount of time to display a countdown (for example 10 seconds), but then snapped to the next measure to base the countdown on. If you have a high bpm, 4 measures is not a long time and countdowns will appear very often. Also time signatures such as 1/x would produce countdowns in pretty much any brief break in notes.

2024-05-14 20:48 UTC, RileyTheFox commented on YARG.Core/Engine/BaseEngine.Generic.cs
> +            if (
I saw you mentioned in the Discord that it may be better to "parse" countdowns ahead of time instead of calculating when they'll be at runtime and I do think that will be better. You could create a `Countdown` object which stores the start and end time (plus any tick or measure information if needed), store a list of them and then just check for when they start and end.

Refer to `GetSoloSections` in BaseEngine.Generic.cs for how that could possibly be done

2024-05-14 20:48 UTC, RileyTheFox commented on YARG.Core/Engine/BaseEngine.Generic.cs
> +         public StarPowerPhraseHitEvent?  OnStarPowerPhraseHit;
Some weird spacing has been added here

2024-05-14 20:48 UTC, RileyTheFox commented on YARG.Core/Engine/Drums/DrumsEngine.cs
> +                     DrumsAction.RedDrum    => (int) FourLaneDrumPad.RedDrum,
Some more weird spacing

2024-05-14 20:48 UTC, RileyTheFox commented on YARG.Core/Engine/Guitar/GuitarEngine.cs
> +            if (State.CountdownMeasuresLeft > 1)
This should be alright, but if you can please test if the countdown end times are deterministic so that the same overstrums are always cancelled in both real run and replay runs.

2024-05-15 15:54 UTC, Purplo-cf commented on YARG.Core/Engine/BaseEngine.Generic.cs
> +            if (
Okay, how does this sound?

- [ ] Replace BaseEngineState.CountdownMeasuresLeft with ActiveCountdownEndTick
- [ ] Create new ChartEvent subclass Countdown and store start and length in seconds and ticks
- [ ] Create a protected Countdowns List property on BaseEngine that stores Countdowns
- [ ] Create private GetCountdowns() method that runs after GetSoloSections() that populates the list. Compare note spacing and create a Countdown instance if any notes are further than 10 seconds apart

    - Creating countdowns based off of absolute time instead of the current time signature should address your concern below. It will also display countdown numbers <4 in low BPM songs, but that may not be an issue.
    - Looping through the entire chart twice for each player is a little clunky, but there could be room here to add a OnChartAvailable callback once the chart data is converted for the current engine

- [ ] Change BaseEngine.Generic.UpdateTimeVariables() logic
   1. If Countdowns list is empty, move on
   2. If Countdowns list is populated and State.ActiveCountdownEndTick is null, compare the current tick against the start ticks and durations of the stored Countdowns
   3. If this is the first tick that enters one of the stored Countdowns, calculate length in measures based off of the current State.TicksEveryMeasure, round down so that the Countdown ends at the start of the first measure that contains a note
   4. Set State.ActiveCountdownEndTick to the rounded value **end**
   5. If State.ActiveCountdownEndTick is not null and measureCount > lastMeasureCount, calculate measuresLeft from the current tick to the stored value, and invoke OnCountdownChange(measuresLeft) as it currently exists

- [ ] Change Engine prevent overstrum/overhit logic so that it is only prevented if State.CurrentTick < State.ActiveCountdownEndTick

2024-05-15 16:31 UTC, RileyTheFox commented on YARG.Core/Engine/BaseEngine.Generic.cs
> +            if (
> Creating countdowns based off of absolute time instead of the current time signature should address your concern below. It will also display countdown numbers <4 in low BPM songs, but that may not be an issue.

You could add a minimum measure count as well but the algorithm which decides what makes a countdown can be finalised another time.

> Looping through the entire chart twice for each player is a little clunky, but there could be room here to add a OnChartAvailable callback once the chart data is converted for the current engine

Looping the data twice is fine. It happens once when the engine is initialized and having callbacks just adds unneeded complexity.

> Change Engine prevent overstrum/overhit logic so that it is only prevented if State.CurrentTick < State.ActiveCountdownEndTick

Generally any hit logic should be using time as a comparison, not ticks (because time is a continuous value while ticks are discrete values). I would also opt for a boolean instead, such as `State.IsCountdownActive` which is enabled whenever a countdown is currently present. This way the condition is simple: If a countdown is active, prevent the overstrum. No need to check ticks or times

2024-05-15 18:31 UTC, Purplo-cf commented on YARG.Core/Engine/Guitar/GuitarEngine.cs
> +            if (State.CountdownMeasuresLeft > 1)
Is the below test process sufficient (after implementing the changes above) ?

- Set up a dummy chart with guitar, bass, and drum notes at the beginning and end, with a blank section in the middle
- Run all 3 instruments through the chart twice
    1. One run where an overstrum in the very beginning, middle, and end of the countdown still maintains the combo
    2. One run where an overstrum right before and right after the countdown breaks the combo

Also, do you have a preferred format for reviewing the results, or is it more of an honors system kind of deal?

2024-05-15 19:58 UTC, RileyTheFox commented on YARG.Core/Engine/Guitar/GuitarEngine.cs
> +            if (State.CountdownMeasuresLeft > 1)
> Set up a dummy chart with guitar, bass, and drum notes at the beginning and end, with a blank section in the middle

Yeah this is fine. I usually make test charts to simplify testing specific scenarios.
> * Run all 3 instruments through the chart twice
>   
>   1. One run where an overstrum in the very beginning, middle, and end of the countdown still maintains the combo
>   2. One run where an overstrum right before and right after the countdown breaks the combo

Just do 1 run where you do both at the same time. I would honestly just bind strum to scroll wheel or something and spam inputs so you get as many inputs close to the countdown times to test with as possible.

> Watch the replay data and confirm the same behavior and score

I almost never watch the replay itself. What I do is utilize our logging system and spam logs to the console, then compare the results from the "real run" and the replay simulation using the History menu's "Analyze" button (unique to the `engine-refactor` branch)

Personally what I would do is output a log when the overstrum gets cancelled by the countdown (make it say something like "`Overstrum cancelled by countdown at {time}`"), and then a log for when an overstrum is allowed through ("`Overstrummed at {time}`" for example). I copy the console output from the real run and save it somewhere. Then I clear my console and then analyze the replay and copy its console output. I filter out any garbage (like the script link formatting) then use [WinMerge](https://winmerge.org/?lang=en) to compare the 2 outputs for any differences.

You can see the engine code is littered with Trace logs throughout for testing and debugging. These are filtered out by default because the minimum log level in YARG is Debug when in editor. You can use the Debug or Trace level if you like, but you'll have to filter out a lot more logs if you use Trace so when I need to be really specific I just use Debug (or create a new temporary log level lol)

> Also, do you have a preferred format for reviewing the results, or is it more of an honors system kind of deal?

Not really. Just evidence that events from the real run and the replay have identical timings is enough because that's all that really matters.

2024-05-21 16:54 UTC, Purplo-cf commented on YARG.Core/Engine/BaseEngine.Generic.cs
> +            if (
Okay, everything discussed above should be implemented now.
After changes to the engine this week, a lot has been moved around and most of the countdown window detection is happening in GenerateQueuedUpdates() instead of UpdateTimeVariables() now.

The new GetWaitCountdowns method is properly accounting for changes in time signature mid-chart, which the last version (and the last me) didn't think about at all.

I'm still making assumptions about one consistent tempo per time signature that it picks up, but I this seems like a good point to check in before I make this even more convoluted...

2024-05-21 16:55 UTC, Purplo-cf commented on YARG.Core/Engine/Guitar/GuitarEngine.cs
> +            if (State.CountdownMeasuresLeft > 1)
Dummy chart test was a success

2024-06-13 01:06 UTC, RileyTheFox commented
Hope you don't mind the wait on this PR. Been extremely busy with lots of changes and refactors myself so haven't had the chance to look at it fully and test it.

From a glance everything looks fine but I just need to put it through some tests and that eats up a lot of time which I need to put into other things at the moment. So long as this PR doesn't get riddled with merge conflicts down the line it should be pretty much ready for me to merge it in when I get the chance.

If I come across anything that needs changing when I get around to testing it I'll report back.

2024-06-13 02:01 UTC, Purplo-cf commented
No worries! I'm learning a lot about how everything fits together. I've had time to fuss with this since the original PR and it's in a much better state now

2024-06-21 20:27 UTC, RileyTheFox commented
@Purplo-cf try not to merge commits from other branches in because it includes those changes as part of the PR. Rebase and force-push if necessary instead.

2024-06-23 19:08 UTC, RileyTheFox requested changes

2024-06-23 19:08 UTC, RileyTheFox commented on YARG.Core/Engine/BaseEngine.Generic.cs
> +                    State.IsWaitCountdownActive = IsTimeBetween(WaitCountdowns[State.CurrentWaitCountdownIndex].Time, previousTime, nextTime);
The countdown should not be started like this. The countdown's time being in between the previous frame and the next frame does NOT guarantee that the next engine update is the countdown's time. 

If an update is queued before it (such as strum leniency timer) and both are between the previous and next frame, then the countdown will be started before its actual time, which could lead to issues.

Engine state changes should never be made in the generation of queued updates. All this function should do is queue times which the engine will be ran at in between the previous and next frame. Any state changes MUST occur within the Engine update loop somewhere, which starts from [here](https://github.com/YARC-Official/YARG.Core/blob/0addf7f4b4275d1fecd3a72885a377d19209d602/YARG.Core/Engine/BaseEngine.cs#L381).

2024-06-23 19:08 UTC, RileyTheFox commented on YARG.Core/Engine/Drums/DrumsEngine.cs
> +                YargLogger.LogFormatTrace(this.GetType().Name+" overhit prevented during WaitCountdown at time: {0}, tick: {1}", State.CurrentTime, State.CurrentTick);
Concatenating the type name results in a string allocation, even if the log level is above Trace. Put it as a parameter, but realistically I wouldn't log the type at all as it's not necessary.

2024-06-23 19:08 UTC, RileyTheFox commented on YARG.Core/Engine/Guitar/GuitarEngine.cs
> +                YargLogger.LogFormatTrace(this.GetType().Name+" overstrum prevented during WaitCountdown at time: {0}, tick: {1}", State.CurrentTime, State.CurrentTick);
Same comment as put in DrumsEngine

2024-06-24 00:01 UTC, Purplo-cf commented on YARG.Core/Engine/BaseEngine.Generic.cs
> +                    State.IsWaitCountdownActive = IsTimeBetween(WaitCountdowns[State.CurrentWaitCountdownIndex].Time, previousTime, nextTime);
Oh weird. The first version of this _was_ started from `UpdateTimeVariables` but I had to move it to get it working after pulling the latest `engine-refactor` changes like a month ago. I put it back and it's working now, so that makes this much simpler!

2024-06-24 00:12 UTC, RileyTheFox requested changes

2024-06-24 00:12 UTC, RileyTheFox commented on YARG.Core/Engine/BaseEngine.Generic.cs
> -
You still need to queue the update for the countdown to start. The whole point of this part is you're *queuing* the update to happen for future execution. You don't want to directly modify countdown status here, you just want to queue the **time** when it should happen. The state change then happens in UpdateTimeVariables when it is invoked on the countdown's exact time.

So here you still need to check if the next countdown to happen is between the previous and next time, if so, queue its time and then have the UpdateTimeVariables portion handle the enabling/disabling of it. Make sure to queue the start and end time appropriately.

If you're not sure what I mean by this, look at any part of the GuitarEngine code in `GenerateQueuedUpdates` and look what it does. None of it modifies state, just checks timers or note times and queues updates as appropriate. Then when the engine is executed at that update's time, the state change will occur

2024-06-24 02:42 UTC, Purplo-cf commented on YARG.Core/Engine/BaseEngine.Generic.cs
> -
Thanks, I put the queued updates back in, and added a couple of log statements to compare the times that the countdowns are turned on and off, compared to the expected start and end times. Here's what I got on the guitar part for Won't Get Fooled Again
<img width="706" alt="image" src="https://github.com/YARC-Official/YARG.Core/assets/33099317/ae58cac3-6387-447b-b8ae-5035d2b7e713">

2024-06-25 15:38 UTC, RileyTheFox requested changes

2024-06-25 15:38 UTC, RileyTheFox commented on YARG.Core/Engine/BaseEngine.Generic.cs
> +                    if (IsTimeBetween(changeTime, previousTime, nextTime))
Tested this PR and discovered that this condition is not passing in runs except for the start and end times. All the measure times in between are not passing this, causing the update times to be inconsistent.

Comparatively in replays this condition does pass, but only for odd amounts of measures.

Log dump of real run: https://pastebin.com/yWRdRr4B
Log dump of replay: https://pastebin.com/kFasQwjy

I've attached a patch with additional logging to help you debug this
[countdown logging.patch](https://github.com/user-attachments/files/15973820/countdown.logging.patch)

2024-06-25 15:38 UTC, RileyTheFox commented on YARG.Core/Engine/BaseEngine.Generic.cs
> +                    UpdateCountdown(countdownMeasuresRemaining);
This is not being called at consistent times for any measures in between the start and end. This is ok for the intermittent times in between measures, but when the `countdownMeasuresRemaining` value changes, the time of this should ideally be getting queued but as mentioned in the previous comment, something is preventing that.

2024-06-25 20:18 UTC, Purplo-cf commented
`GetRemainingMeasures` should be sending out the correct queue times now. I'm also throttling `UpdateCountdown` now so that it only fires when the number of remaining measures has changed. The logs should be much easier to read now:

Actual run:
https://pastebin.com/CWHtRAP6

Replay of same run:
https://pastebin.com/kpeT8HkF

2024-06-25 20:47 UTC, RileyTheFox requested changes

2024-06-25 20:47 UTC, RileyTheFox commented on YARG.Core/Chart/Events/WaitCountdown.cs
> +        public int GetRemainingMeasures(uint currentTick, out bool needsUpdate)
I don't think this is the best way of handling checking for a change in measures. I would opt for making `_measuresLeft` into a public get private setter property that the BaseEngine can access. This function should only handle returning however many measures are left, not signalling if something should be updated.

2024-06-25 20:47 UTC, RileyTheFox commented on YARG.Core/Engine/BaseEngine.Generic.cs
> +                    if (needsUpdate)
Instead of using a bool from the function call above, just store the remaining amount of measures before calling the function (the public property) into a local variable, then call the function and compare the 2 values for the condition

2024-06-25 20:47 UTC, RileyTheFox commented on YARG.Core/Chart/Events/WaitCountdown.cs
> +        public const float MIN_SECONDS = 9;
What was the need for this change?

2024-06-25 20:47 UTC, RileyTheFox commented on YARG.Core/Engine/BaseEngine.Generic.cs
> +                            firstCountdownFrame = true;
Instead of having this flag to work around an issue, I'd prefer to just call UpdateCountdown() here instead.

2024-06-25 20:47 UTC, RileyTheFox commented on YARG.Core/Engine/BaseEngine.Generic.cs
>                      int countdownMeasuresRemaining = activeCountdown.GetRemainingMeasures(State.CurrentTick, out bool needsUpdate);
With the previous comment, change this part into an `else` statement. This will prevent the countdown updating part from executing if a countdown was not active and has just been started in this call.

2024-06-25 20:57 UTC, Purplo-cf commented on YARG.Core/Chart/Events/WaitCountdown.cs
> +        public const float MIN_SECONDS = 9;
Just calibrating. There was a 7 measure wait in my test chart (3/4@120bpm) that was getting skipped because it was just under the threshold, but still felt long enough to show a countdown. The original 10 second threshold was an arbitrary starting point.

2024-06-25 21:51 UTC, Purplo-cf commented on YARG.Core/Engine/BaseEngine.Generic.cs
> +                            firstCountdownFrame = true;
No longer necessary. The new logic for detecting a change in `MeasuresRemaining` gets around the original issue that this was trying to fix.

2024-06-27 00:44 UTC, RileyTheFox requested changes
Discovered some more inconsistent update times through some testing:

First attempt:
![image](https://github.com/YARC-Official/YARG.Core/assets/29326764/17d1c935-e93b-4341-a59c-95b045d2549e)

Second attempt:
![image](https://github.com/YARC-Official/YARG.Core/assets/29326764/0a313f17-6495-45fc-aada-fc8b480f159f)

Blank lines added where logs are missing just so the other entries line up.

I think I know what the culprit is: Large gaps in-between input times results in some of the update times for countdowns getting skipped. The first time I came across it I was confused but had a theory, then I tested that theory and it was confirmed. In the second attempt I waited around 5 seconds into the song before pressing anything and there was a few missing updates.

Song used for testing was Soulless 5 as it has an 18 second countdown right at the start so is easy to test with.

2024-06-27 01:18 UTC, RileyTheFox commented
Seems to have been a bug in the general update loop for the engine. Will keep testing things however

2024-07-12 14:10 UTC, RileyTheFox approved these changes

2024-07-12 15:21 UTC, merged