Change points awarded per vocals phrase for lower difficulties
YARC-Official/YARG.Core pull request #174
Opened 2024-05-29 03:25 UTC by poliwhirlge

Up to now we've been awarding 2000 base points per completed phrase regardless of difficulty, this PR scales the values for lower difficulties similarly to how RB's scoring works.

2024-05-29 22:19 UTC, EliteAsian123 requested changes

2024-05-29 22:19 UTC, EliteAsian123 commented on YARG.Core/Engine/Vocals/VocalsEngineParameters.cs
> +        public int PointsPerPhrase { get; private set; }
Make sure the engine param is added to the serialization methods!

2024-05-29 22:19 UTC, EliteAsian123 commented on YARG.Core/Engine/Vocals/VocalsEngine.cs
> +        protected int POINTS_PER_PHRASE;
It may be best to just completely remove this field and access the amount of points from the engine params

2024-05-30 00:55 UTC, poliwhirlge commented on YARG.Core/Engine/Vocals/VocalsEngineParameters.cs
> +        public int PointsPerPhrase { get; private set; }
Yeah I thought that this was for user configured presets, but it's for replays, my bad.

2024-06-02 20:39 UTC, merged