Drum velocity core
YARC-Official/YARG.Core pull request #178
Opened 2024-06-07 20:17 UTC by Purplo-cf

Hit logic for accepting velocity-based inputs on DrumNotes.

Added properties to DrumNote, DrumsEngine, and DrumEngineState for storing velocity data on hit.

Updated MidReader to accept "ENABLE_CHART_DYNAMICS" text event without brackets.

2024-06-07 20:33 UTC, Purplo-cf commented on YARG.Core/Chart/Notes/DrumNote.cs
Velocity bonus points are awarded based on the last "pressed" amount of this input compared to the VELOCITY_THRESHOLD constant.

Default: Ghosts are <= VELOCITY_THRESHOLD, Accents are >= (1 - VELOCITY_THRESHOLD).

Context sensitive: A note on this pad was hit within the last 3 seconds. Ghosts notes will accept (lastVelocity - VELOCITY_THRESHOLD) if it is higher than the default VELOCITY_THRESHOLD, and vice versa for Accent notes

2024-06-07 20:37 UTC, Purplo-cf commented on YARG.Core/Engine/Drums/DrumsEngineState.cs
Storing the last input axis value in DrumsEngineState as HitVelocity. Gets sent to DrumNote.SetHitState()

2024-06-07 20:41 UTC, Purplo-cf commented on YARG.Core/Engine/Drums/DrumsEngine.cs
Notes are awarded a velocity bonus of (POINTS_PER_NOTE * 0.5), when velocity conditions are met. This is currently a bonus of +25 for a total of 75 points in Standard Drums or 85 points in Pro Drums.

This logic is consistent with how GHWT handled accent bonuses, but I couldn't find any actual numbers for what Clone Hero does here

2024-06-08 03:16 UTC, EliteAsian123 requested changes
Hi, thanks for the PR, please see the requested changes below, and on the YARG-side PR.

Thanks!

2024-06-08 03:16 UTC, EliteAsian123 commented on YARG.Core/Chart/Notes/DrumNote.cs
> +        private const float SITUATIONAL_VELOCITY_WINDOW = 3;
These should be moved to the engine or even be made into engine parameters (see comments below on why)

2024-06-08 03:16 UTC, EliteAsian123 commented on YARG.Core/Chart/Notes/DrumNote.cs
> +        public float HitVelocity = -1;
Instead of using `-1` as a "not set" value, use a nullable float (`float?`) instead, which makes it explicit that `null` is not set.

2024-06-08 03:16 UTC, EliteAsian123 commented on YARG.Core/Chart/Notes/DrumNote.cs
> +            SetHitState(hit, includeChildren);
This code for checking previous notes should be moved to the YARG engine file as how these things are calculated can be changed based on what engine is being used. The note class should only contain the data and methods to manipulate the data instead of actual logic.

2024-06-08 03:16 UTC, EliteAsian123 commented on YARG.Core/Engine/Drums/DrumsEngine.cs
> +
Once the velocity check is moved into the YARG engine class the `AwardVelocityBonus` check shouldn't be needed and the bonus can just be directly added to the score.

2024-06-08 03:16 UTC, EliteAsian123 commented on YARG.Core/Engine/Drums/DrumsEngineState.cs
> +        public float HitVelocity = 1;
Like in the note class, this should be a nullable float, much like the nullable int above.

2024-06-09 19:46 UTC, EliteAsian123 requested changes
Hello!

It appears two of my suggestions have not been taken into account so I've requested changes again below.

If there is a reason you're not doing this any of these, please let me know!

2024-06-09 19:46 UTC, EliteAsian123 commented on YARG.Core/Engine/Drums/DrumsEngine.cs
> +        private const float SITUATIONAL_VELOCITY_WINDOW = 1.5f;
These should both be made into engine parameters so they can be customized with engine presets.

2024-06-09 19:46 UTC, EliteAsian123 commented on YARG.Core/Engine/Drums/DrumsEngine.cs
> +                hitNote.AwardVelocityBonus = awardVelocityBonus;
Instead of using a variable stored within the note class here, the score can probably just be manipulated directly. This eliminates the need for an extra bool within the note class.

2024-06-10 02:42 UTC, Purplo-cf commented on YARG.Core/Engine/Drums/DrumsEngine.cs
> +        private const float SITUATIONAL_VELOCITY_WINDOW = 1.5f;
Oh duh, EngineParameters, sorry! I thought you just meant to move the constants into the DrumsEngine file lol

2024-06-10 02:54 UTC, Purplo-cf commented on YARG.Core/Engine/Drums/DrumsEngine.cs
> +                hitNote.AwardVelocityBonus = awardVelocityBonus;
I wanted to try a Deadly Dynamics modifier after this and wasn't sure how else to do it. The score is currently being added after the hit state is set to true. With the modifier, we would have to check the velocity before setting the hit state in case we need to count it as a miss instead.

With that and the bonus points check I'm storing the pass/fail result in the note so we only have to evaluate that once.

2024-06-10 21:21 UTC, EliteAsian123 commented on YARG.Core/Engine/Drums/DrumsEngine.cs
> +                hitNote.AwardVelocityBonus = awardVelocityBonus;
Yes so instead, what can happen, is that this is calculated right above line 73 here and the note can be denied the hit in the YARG drums engine. As for the score, it can be added after the note is hit, or can be passed into the `HitNote` method somehow.

https://github.com/YARC-Official/YARG.Core/blob/bb8829a0d8620f26f07ebc799a0248dbad08404d/YARG.Core/Engine/Drums/Engines/YargDrumsEngine.cs#L70-L79

2024-06-10 21:24 UTC, EliteAsian123 requested changes
A few things about the engine parameters. Be sure to check my comment on the non-resolved issues above!

2024-06-10 21:24 UTC, EliteAsian123 commented on YARG.Core/Engine/Drums/DrumsEngineParameters.cs
> +
These should be properties (`{ get; private set; }`) and be set through the constructor. Also, make sure to serialize these new properties!

[Here](https://github.com/YARC-Official/YARG.Core/blob/engine-refactor/YARG.Core/Engine/Guitar/GuitarEngineParameters.cs) is an example from the guitar params.

2024-06-10 21:24 UTC, EliteAsian123 commented on YARG.Core/Engine/Drums/DrumsEngine.cs
> -    {
Random space appeared here

2024-06-11 20:55 UTC, Purplo-cf commented on YARG.Core/Engine/Drums/DrumsEngine.cs
> +                hitNote.AwardVelocityBonus = awardVelocityBonus;
Thanks, I put the logic where you suggested and I'm no longer storing `ApplyVelocityBonus` in each individual note. The `DrumsEngine.ApplyVelocity` method now just returns a bool on whether a hit qualifies for bonus points. That bool goes into a new `HitNote` overload in `YargDrumsEngine`. I left a TODO in there on where I think we can capture that bool and go to `MissNote` instead if Deadly Dynamics is on.

2024-06-13 01:17 UTC, EliteAsian123 requested changes
One small nitpick and this should be good to go! I'm not going to worry about the art on the YARG-side PR and I'll implement the UI part of the engine parameters for you. Thanks!

2024-06-13 01:17 UTC, EliteAsian123 commented on YARG.Core/Engine/Drums/Engines/YargDrumsEngine.cs
> +        protected void HitNote(DrumNote note, bool awardVelocityBonus, bool activationAutoHit)
Creating an overload here isn't the clearest. It's probably better to call this something else or to just put it above with the call to the original `HitNote`.

2024-06-13 01:57 UTC, Purplo-cf commented on YARG.Core/Engine/Drums/Engines/YargDrumsEngine.cs
> +        protected void HitNote(DrumNote note, bool awardVelocityBonus, bool activationAutoHit)
I moved it up to the original `HitNote` like you suggested, since it's only being used once

2024-06-13 01:58 UTC, Purplo-cf commented
> I'll implement the UI part of the engine parameters for you.

Thanks! For future reference, what other files should I have updated?

2024-06-14 19:12 UTC, EliteAsian123 commented
> Thanks! For future reference, what other files should I have updated?

It's quite simple, keep a look out for the commits I'll make which will address this after it's merge!

2024-06-14 19:12 UTC, merged