Refactor Replay Serialisation/Deserialisation
YARC-Official/YARG.Core pull request #180
Opened 2024-06-09 01:25 UTC by RileyTheFox

The old code for this was very messy and all over the place, required you to jump through multiple classes to understand the structure of the files. This PR moves writing and reading of replay files all into one static class, instead of relying on the types to serialise/deserialise themselves. This aims to make it clearer how the files are structured and to make amends in the future.

Goal is to remove all the Serialize/Deserialize functions from the types themselves (except when it is needed to be shared with other code, such as YargProfile or color profiles)

2024-08-11 17:32 UTC, sonicfind requested changes

2024-08-11 17:32 UTC, sonicfind commented on YARG.Core/Replays/ReplaySerializer.Sections.cs
> +            }
The only instance where something like this is more okay would be if you were using composition for all the types instead of inheritance. What we're doing here is basically taking bad points of both designs and making something overall worse.

For example: `DrumsStats`, `GuitarStats`, `ProKeysStats`, `VocalsStats`; all of these **ARE** extensions on the `BaseStats`, so it makes sense to utilize inheritance to share that information. However, the code that uses it here interprets them all instead as classes that **CONTAIN** a `BaseStats` type, but only *after* they've already been constructed. It's contradictory architecture.

2024-08-11 17:32 UTC, sonicfind commented on YARG.Core/Replays/ReplaySerializer.Sections.cs
> +            }
It also makes the serialization code structure inconsistent with the de-serialization.

Note that when you serialize all the data, you basically split the function into **two** blocks. The first block handles writing in the base type information while the second block handles writing the subclassed information.

Meanwhile, the de-serialization code has **three** blocks. The first deserializes the values that go in the base type. The second reads in the values that belong to one of the subclasses. Then finally, the third *actually applies the base type information.* This alone is potentially dangerous.

Let's say you update a base type with a new value. You add the write; you add the read; you even remember to alter the version number. But then you test it out in game and it doesn't behave as expected (or worse, you don't see that it doesn't).

Notice how I never mentioned that you *set* the value in the base instance after reading. It's a completely separate operation that won't produce a warning nor error and therefore has to be accounted for - which makes it easily forgettable.

2024-08-25 02:28 UTC, RileyTheFox commented on YARG.Core/Replays/v012/V012ReplaySerializer.cs
I found it useful to keep around to ensure I ported the reading code correctly. It doesn't necessarily need to exist, it just helped me to have it when I started this refactor

2024-09-17 15:39 UTC, closed without merging