Drum Hit SFX Core
YARC-Official/YARG.Core pull request #186
Opened 2024-06-15 19:35 UTC by raphaelgoulart

Companion to https://github.com/YARC-Official/YARG/pull/802

2024-06-16 11:48 UTC, raphaelgoulart commented
Actually marking this as ready to review since it doesn't impact YARG itself (and even fixes a bug with 127-velocity hits not being detected, though maybe not in the best of ways)

2024-06-17 17:11 UTC, RileyTheFox commented on YARG.Core/Engine/Drums/Engines/YargDrumsEngine.cs
> +            if (gameInput.Axis > 0) // For some reason, it's ignoring 127-velocity hits and this fixes it...
Would suggest removing this comment as we discussed why this was the case on Discord. Perhaps replace it with a comment detailing why Axis is used here instead of Button (in regards to the floating point bit values)

Also try to place comments a line above, instead of on the same line as an expression or statement

2024-06-17 20:37 UTC, raphaelgoulart commented on YARG.Core/Engine/Drums/Engines/YargDrumsEngine.cs
> +            if (gameInput.Axis > 0) // For some reason, it's ignoring 127-velocity hits and this fixes it...
Done, sadly I couldn't explain it in briefer terms but hopefully my explanation works. Let me know if there's a better way to clarify it

2024-06-17 20:40 UTC, RileyTheFox commented
Requesting review from @sonicfind as it adds to the audio code which he wrote

2024-06-19 18:22 UTC, sonicfind requested changes
Pretty solid: just need that `_volume` member variable to keep everything in-line.

2024-06-19 18:22 UTC, sonicfind commented on YARG.Core/Audio/DrumSampleChannel.cs
> +                }
Set the `_volume` member variable to the initial value of volume passed to this function. Afterwards,  multiply that by the current `DrumSfx` `StemSettings` value before sending it `SetVolume_Internal()`.

2024-06-19 18:22 UTC, sonicfind commented on YARG.Core/Audio/DrumSampleChannel.cs
> +        }
When `StemSettings.OnVolumeChange` calls this function, multiply the value of `volume` by `_volume` before sending it to `SetVolume_Internal()`.

2024-06-19 18:22 UTC, sonicfind commented on YARG.Core/Audio/DrumSampleChannel.cs
> +        }
Attach the `StemSettings.OnVolumeChange` for DrumSfx to `SetVolume()`

2024-06-19 18:22 UTC, sonicfind commented on YARG.Core/Audio/DrumSampleChannel.cs
> +
Add a `double _volume` member variable here.

2024-06-20 02:17 UTC, sonicfind approved these changes

2024-06-20 02:24 UTC, merged