Refactor .chart parsing to use `YARGChartFileReader`
YARC-Official/YARG.Core pull request #204
Opened 2024-08-18 11:19 UTC by TheNathannator

This ensures parsing behavior consistency between song scanning and chart loading, and fixes a possible issue where closing braces `}` being present in a text event would trip up the parser and make it fail to load.

To support this, I made some changes to some of the .ini classes to un-hard-code their expectance on being used for song.ini files, due to `YARGChartFileReader` relying on that infrastructure in its implementation and results. `YARGChartFileReader.ExtractModifiers` now takes a lookup of allowed modifiers as a parameter, and `IniSection` now takes a constructor argument for known modifiers to use for debug validation.

2024-08-18 23:45 UTC, sonicfind requested changes

2024-08-18 23:45 UTC, sonicfind commented on YARG.Core/MoonscraperChartParser/IO/Chart/ChartReader.cs
> +                                YARGTextReader.SkipWhitespace(ref chartText);
Skipping the whitespace shouldn't be necessary since it's going to skip to the next line in the following `TryParseEvent` call.

2024-08-18 23:45 UTC, sonicfind commented on YARG.Core/MoonscraperChartParser/IO/Chart/ChartReader.cs
> +                            // anchorData.Add(anchor);
We may have to reconsider *this* later, but for now it's fine. It'd go outta scope for the PR.

2024-08-18 23:45 UTC, sonicfind commented on YARG.Core/MoonscraperChartParser/IO/Chart/ChartReader.cs
> +                        throw new Exception("Tick value not in ascending order");
Again, `TryParseEvent` throws in this case

2024-08-18 23:45 UTC, sonicfind commented on YARG.Core/MoonscraperChartParser/IO/Chart/ChartReader.cs
> +                    prevTick = tick;
Another one for the road

2024-08-18 23:45 UTC, sonicfind commented on YARG.Core/IO/YARGChartFileReader.cs
> +        }
We only call this from one location, so adding a special function for that case just to wrap the IniSection construction is unnecessary. Just let the caller handle that detail and only have the two-parameter version. Makes it more explicit.

2024-08-19 02:54 UTC, TheNathannator commented on YARG.Core/MoonscraperChartParser/IO/Chart/ChartReader.cs
> +                                YARGTextReader.SkipWhitespace(ref chartText);
Fair point, I was just ensuring consistent behavior with the other value extraction calls.

2024-08-19 03:00 UTC, TheNathannator commented on YARG.Core/MoonscraperChartParser/IO/Chart/ChartReader.cs
> +            static void ExpectSection(ref YARGTextContainer<TChar> chartText, string section, int sectionIndex)
In practice I'm not sure if this case will ever actually come up as an issue; the resolution and sync track are vital to the chart working correctly, and I'd rather reject charts that are missing these than cover for their mistakes.

The only case this will happen in the wild is is if someone deliberately removed those sections. Moonscraper will always write `[Song]`, `[SyncTrack]`, and `[Events]`, in that order, and I presume Feedback did as well.

2024-08-19 03:02 UTC, TheNathannator commented on YARG.Core/MoonscraperChartParser/IO/Chart/ChartReader.cs
> +                            // anchorData.Add(anchor);
We'll get to it when we're ready for it, no point parsing in something that won't be used until an indeterminate timeframe lol

2024-08-19 03:25 UTC, TheNathannator commented on YARG.Core/IO/YARGChartFileReader.cs
> +        }
I was thinking from an API design perspective with this one, having the default is convenient. But yeah, it's a little superfluous when it's used in just one place.

2024-08-23 17:40 UTC, sonicfind commented on YARG.Core/MoonscraperChartParser/IO/Chart/ChartReader.cs
> +            static void ExpectSection(ref YARGTextContainer<TChar> chartText, string section, int sectionIndex)
The issue is it's hard to call the deliberate removal of those sections and/or the resolution "mistakes" when there really aren't *hard* guidelines or specifications regarding how to handle those situations. In absence of that kind of stuff, they only thing we can go off of is precedence; and currently, the precedence set by the most prevalent and used tools/games that accept the format is to just use default values instead of erroring. 120 bpm with 4/4 time sig for a missing synctrack (which is already handled in MoonSong's construction in the refactor branch) and 192 for a missing resolution value.

Plus you said it yourself: it'd need to be *deliberate*, and they'd only do that if the file still worked.

2024-08-23 17:41 UTC, sonicfind commented on YARG.Core/MoonscraperChartParser/IO/Chart/ChartReader.cs
> +            return song;
You can simplify this function a bit. The main point of importance is that it parses (or attempts to parse) the tick rate of the chart. All the other stuff should be done externally - especially the `ValidateAndApplySettings` call. Just have the function return only the tick rate.

Additionally, going off the whole "not an error" thing, you can move the `[Song]` header check into this function instead. This would allow easily handling the default case. You'd define the tick rate to the default .chart value of 192, then only if the header is found and if `Resolution` rests within it would you override it. Though, I'd still recommend throwing for a resolution of `< 1`, because that'd be stupid.

2024-08-23 18:18 UTC, sonicfind requested changes

2024-08-23 18:18 UTC, sonicfind commented on YARG.Core/IO/Ini/IniSection.cs
> +
Don't wrap this (or its initialization) as "Debug only". I might have a use for this afterwards.

2024-08-23 19:23 UTC, TheNathannator commented on YARG.Core/MoonscraperChartParser/IO/Chart/ChartReader.cs
> +            static void ExpectSection(ref YARGTextContainer<TChar> chartText, string section, int sectionIndex)
I'd much rather have the resolution and sync track be guaranteed to be correct ahead of time, than have other things which might rely on it during parsing have incorrect results due to absence or ordering differences. This might not apply now, but it certainly could in the future with potential refactors.

2024-08-23 19:38 UTC, TheNathannator commented on YARG.Core/MoonscraperChartParser/IO/Chart/ChartReader.cs
> +            static void ExpectSection(ref YARGTextContainer<TChar> chartText, string section, int sectionIndex)
To equate this to a prior situation: my reasoning for this is the same reason as to why we decided to disallow having multiple track names within a MIDI track. It's an ambiguous scenario with no real clear answer other than "set some defaults and hope for the best". Just because it *can* happen doesn't mean we need to accept it, regardless of prior precedence.

To contrast, that change affected quite a few charts out there in the wild, while I expect this to affect no charts whatsoever due to the obscurity of the problem. Allowing it would only cause more potential problems, imo.

2024-08-23 21:15 UTC, TheNathannator commented on YARG.Core/MoonscraperChartParser/IO/Chart/ChartReader.cs
> +            return song;
> especially the `ValidateAndApplySettings` call.

This call relies directly on values read from the metadata section, so IMO it doesn't make much sense to separate the two. This function is as simple as it needs to be, no need to make it simpler just for the heck of it.

2024-08-23 22:00 UTC, sonicfind commented on YARG.Core/MoonscraperChartParser/IO/Chart/ChartReader.cs
> +            return song;
In actuality, it relies on only two things: resolution/tick rate & the `settings` variable. The tick rate can just be returned and `settings` doesn't need to be passed in.

The problem right now is that the name `ReadMetadataSection` doesn't actually match up with what is transpiring in the function.
1. It does read the metadata segment. That's fine. However...
2. It only extracts out the tick rate from the entirety of that section. That detail isn't apparent to a caller through the name.
3. It creates a `MoonSong` object, which leads to the initialization of a bunch of data and separate states. Again, that detail is not apparent in the function name.
4. It then uses the extracted tick rate to modify state in the song and, more importantly, the settings object. Again, not apparent.

Unfortunately, so long as all that stuff remains stays in this one function, there's no sensible way to solve any of those clarity issues without making the function name like one you would see in a weird-ass Java codebase (those bitches are longggggggg).

2024-08-23 22:10 UTC, sonicfind commented on YARG.Core/MoonscraperChartParser/IO/Chart/ChartReader.cs
> +            static void ExpectSection(ref YARGTextContainer<TChar> chartText, string section, int sectionIndex)
> To equate this to a prior situation: my reasoning for this is the same reason as to why we decided to disallow having multiple track names within a MIDI track. It's an ambiguous scenario with no real clear answer other than "set some defaults and hope for the best"

The big difference here is that MIDI has a hard specification, and said specification explicitly states that a midi event of type `03` represents "**the** name of the track", not "**A** name for the track". Therefore, tracks contained in midi files are only in-spec if they contain no more than a single track name. `.chart` doesn't really have an equivalent to midi's specification. It has documentation on the format, but that's from research of how it's been used, not how it's supposed to be used.

And unlike this where these situations are mainly caused through deliberate actions or decisions, the duplicate MIDI track name issues are made through **accident**. They're not the same.

2024-08-24 14:35 UTC, TheNathannator commented on YARG.Core/MoonscraperChartParser/IO/Chart/ChartReader.cs
> +            static void ExpectSection(ref YARGTextContainer<TChar> chartText, string section, int sectionIndex)
They're still a very similar caliber of issue, disregarding standards/documentation. It's a behavior that's colloquially allowed by prior programs/games which we would now be deciding to disallow for correctness.

I was initially against the decision to disallow these multiple track names in .mid, because it was very much a thing that already existed in notable charts. But my opinion was outweighed, and so I conceded, despite it being a compatibility-breaking change.

This change does not have the same compatibility implications. There is no reason for us to allow this, other than the fact that previous games allow it. No existing charts I'm aware of rely on this behavior to function correctly; other than that one chart with a quoted resolution that I pointed out in the Discord (which we can account for in other, more correct ways).

Even more to the point, this being a very deliberate action is even more reason *not* to support it, while the .mid issue being accidental and on a somewhat notable scale would be grounds enough for me to want to implement a workaround, rather than require charts to be fixed up manually.

2024-08-24 15:27 UTC, TheNathannator commented on YARG.Core/MoonscraperChartParser/IO/Chart/ChartReader.cs
> +            return song;
> That detail isn't apparent to a caller through the name.

This is also a private method, whose details probably *should* be looked at if someone is analyzing the code in any level of detail, IMO.

I consider the reading of the resolution value to still be a detail related to the metadata section. The fact that *only* resolution is read doesn't particularly matter, because most of the remaining properties aren't relevant to the actual parsing of the chart (and the ones that do matter are already handled at scan time, through `ParseSettings`).

- By that logic it's a little superfluous to include *all* the properties in `YARGChartFileReader.METADATA_MODIFIERS`, and so I'm fine with removing the unnecessary ones.
- Side-note: I find it odd how .chart properties are also included in the map of song.ini properties in the scanning code. It makes it less-than-obvious on how those are converted to the corresponding song.ini properties; but that's something for a separate discussion.

The creation of a `MoonSong` object relies directly on the resolution value, and so the easiest place to stick its creation was in there. I do agree that part is odd though, so I'll move it. Returning *just* the resolution doesn't make the most sense with a method that's supposed to contain details though, so I'm thinking a struct would be better/clearer (even if it's just got one member currently).

2024-08-29 05:48 UTC, sonicfind commented on YARG.Core/MoonscraperChartParser/IO/Chart/ChartReader.cs
> +            static void ExpectSection(ref YARGTextContainer<TChar> chartText, string section, int sectionIndex)
> Even more to the point, this being a very deliberate action is even more reason not to support it

What's important here is *why* someone would deliberately remove the `[Song]` section. Think about how Moonscraper exports .chart files. Every time, the `[Song]` section is filled with different metadata: song name, artist, album, year, offset, Resolution, Player2, Difficulty, PreviewStart, PreviewEnd, genre, MediaType, and any music streams.

How many of those modifiers have any actual use in any games? You could argue that the basic song info metadata is... but that's what we use song.ini for. And neither CH or YARG utilize the stream paths (because that'd be a huge can of worms). It wouldn't surprise me if someone decided to save just a little bit more room by removing any of that duplicate and/or unused information.

That leaves the resolution. Well, for CH, even before reading this section, the resolution is already defaulted to 192. With that being the case, of course there would be no harm in just stripping that out too. So now all that's left is... nothing? Well, might as well removing that entire section then! It still works in CH! Same with synctrack... although that's only useful for a song that is entirely 120bpm and 4/4 (exceedingly rare - unless you like Big And Chunky).

It's purely a game of bytes, saving as much space as you can manage while still being a valid playable chart in the main most popular five-fret fan game in community. These *have a purpose*, and so long as a well-defined explicit specification does not exist for the format, longstanding precedence rules.

> while the .mid issue being accidental and on a somewhat notable scale would be grounds enough for me to want to implement a workaround

Unlike .mid, where there does exist a well-defined explicit specification created and deliberated by numerous groups of important people and corporations; a specification designed to provide guidelines on how midi files have to be formatted to ensure fully consistent behavior across the many tools that accept them.

For the majority of times we've seen people ask about the track name restriction, it's the result of an accidental misunderstanding of Reaper to some degree. As a result, they gain new information about the format as they aim to fix it, and in the end, the file usually ends up tidier (bonus: **less data!**). Hiding the error would only lead to people never learning correct patterns, which can have some very adverse effects. I'd rather not risk having multiple instances of this happening under someone's nose.
![image](https://github.com/user-attachments/assets/838658da-ceac-4b69-a7aa-1eb60103af44)

The only midi spec violation we must allow is ignoring sysex for MidiNote resets: because, unfortunately, besides Phase Shift, some official Rock Band midi files contain that error (and I mean on disc and/or direct DLC). It'd be *really* bad to not allow those to work. That being said, no one uses tools that violate that on export these days, so it's not as big of a deal.

These are two wildly different situations with massively different implications.

2024-09-24 19:45 UTC, closed without merging