Customizable Highway Presets
YARC-Official/YARG.Core pull request #220
Opened 2024-10-18 11:08 UTC by thomeval

This PR introduces Highway Presets to YARG.Core. For details, see the associated PR on the YARG repo.

2024-10-18 15:49 UTC, EliteAsian123 requested changes
Now, please let me know if I'm wrong here, however, I think it's actually better to handle highway presets much like themes are in this case: don't store them in replays (only the GUID) and move the class to YARG instead of YARG.Core. 

The reason why is because these will eventually be expanded to include textures (or file paths to textures) so you can customize the highways even more. In that case, storing the highway preset in the replay doesn't make sense since everyone wouldn't have said texture at said path. This is essentially the same reason why themes aren't store in replays (only the GUIDs so if the user _has_ the theme, then it's applied).

Obviously, it is possible that in the future we will store them in replays, however, then there's an explicit content risk, and potentially other risks. Because of this I think it's better to cross that bridge when we get to it, and after we discuss it a little more.

2024-10-23 13:51 UTC, thomeval commented
I've removed HighwayPresets from ReplayData as requested.

2024-11-08 02:24 UTC, EliteAsian123 requested changes
Hello! Sorry for the late review. Just some changes and this should be good to go! I'll review the other PR shortly.

2024-11-08 02:24 UTC, EliteAsian123 commented on YARG.Core/Game/Presets/HighwayPreset.cs
> +        }
This shouldn't be needed I believe, since they're not used in replays

2024-11-18 23:41 UTC, merged