Engine support for treating solo frets separately from normal frets
YARC-Official/YARG.Core pull request #224
Opened 2024-11-27 20:28 UTC by wyrdough

This PR adds support for solo buttons as found on Rock Band guitars and the Riffmaster.

During a solo section, all notes are treated as if they are tap notes when the solo buttons are used.

2024-11-27 22:19 UTC, RileyTheFox commented
We decided a while ago that the change in logic solo buttons provide was something we were not going to have as it provides an advantage over guitars which don't have solo buttons.

We've considered this being added as some kind of modifier/engine setting but it's not been thought about too much.

2024-11-28 21:05 UTC, wyrdough commented
Changed to an engine parameter. Logic changes as suggested on Discord to prevent tap logic being triggered while standard buttons are held.

2025-01-06 20:59 UTC, EliteAsian123 requested changes
Hello, thanks for the PR!

Please review the comments below for the changes I requested.

After that fix, I just need to know if this conflicts with any changes in the `engine-fixes` branch and whether or not this can be merged right now, or if we should wait (@RileyTheFox).

2025-01-06 20:59 UTC, EliteAsian123 commented on YARG.Core/Engine/Guitar/GuitarEngine.cs
> +            if((int) fret >= 10) {
Please please please do not use "terrible hacks" within PRs. 

Before the big rewrite of v0.12, I made the mistake of merging PRs with hacks in them. They build up over time, and the codebase's quality just plummets because of that. 

Unfortunately, because of this, before this PR is merged this needs to be fixed.

2025-01-06 20:59 UTC, EliteAsian123 commented on YARG.Core/Engine/Guitar/GuitarEngine.cs
> +            // FIXME: This is a terrible hack
Same here

2025-01-07 03:16 UTC, wyrdough commented on YARG.Core/Engine/Guitar/GuitarEngine.cs
> +            if((int) fret >= 10) {
That is there so that the solo frets don't have to be special cased everywhere ButtonMask is used. I called it a hack, but I can't really think of a better way to do it, TBH.

2025-01-19 19:09 UTC, wyrdough commented on YARG.Core/Engine/Guitar/GuitarEngine.cs
> +            if((int) fret >= 10) {
Ok, I changed it to make the input button mask a ushort to accommodate the extra buttons and then calculate an effective button mask which is a bitwise or of the two sets of buttons to be used where ButtonMask was previously being used so that the solo buttons still act as regular buttons outside of solos.

If you can think of a better strategy here, I'm all ears.

2025-07-04 18:27 UTC, merged