WIP: Song scanning
YARC-Official/YARG.Core pull request #32
Opened 2023-08-07 14:58 UTC by sonicfind

2023-08-07 22:29 UTC, TheNathannator reviewed
Just a few quick comments I have from taking a quick look, haven't gotten a chance to review thoroughly lol

2023-08-07 22:29 UTC, TheNathannator commented on YARG.Core/InstrumentEnums.cs
> +        UNKNOWN_PRO,
Preferred style for enums is PascalCase, not CONST_CASE.

2023-08-07 22:29 UTC, TheNathannator commented on YARG.Core/Song/Deserialization/Ini/IniModifier.cs
> +        public SortString SORTSTR
Property names should be PascalCase as well, preferably also without shortening.
```diff
- public SortString SORTSTR
+ public SortString SortString
```
This one's a little odd since it results in the same name as the type lol, but that happens sometimes.

2023-08-07 22:29 UTC, TheNathannator commented on YARG.Core/Song/Deserialization/Ini/IniHandler.cs
> +                { "early_hit_window_size",                new("early_hit_window_size", ModifierNodeType.STRING) },
Some of these .ini tags are an odd inclusion, do we really need to handle *all* of these? No point checking what we never use.

2023-08-07 22:29 UTC, TheNathannator commented on YARG.Core/Song/Deserialization/Ini/IniHandler.cs
> +                { "sysex_slider",                         new("sysex_slider", ModifierNodeType.BOOL) },
Same sentiment with these tags. There's no reason to be able to enable or disable SysEx events, we're never gonna use these lol

2023-08-07 22:29 UTC, TheNathannator commented on YARG.Core/Song/Deserialization/YARGBinaryReader.cs
> +#nullable enable
Probably something we should enable for the whole project if we're gonna use it lol

2023-08-07 22:29 UTC, TheNathannator commented on YARG.Core/Song/Deserialization/YARGFile.cs
> +        public byte* Data => _data;
Really should just use a `byte[]` or `ReadOnlyMemory<byte>` here or something, GCHandles are expensive and you can easily get a `byte*` from a `byte[]` by using a `fixed` statement where they're needed.

2023-08-09 01:17 UTC, sonicfind commented on YARG.Core/Song/Deserialization/YARGBinaryReader.cs
> +#nullable enable
**For the love of God, please figure out how to do that**

To be real, yes, it does. Turning it on actually led to me finding a potential bug before production.

2023-08-09 03:03 UTC, TheNathannator requested changes
Took a much more thorough look this time, I definitely think a lot of this is over-engineered but it's nothing I wouldn't be able to work with lol

A lot of these requests are just making constants for things and de-duplicating code where possible. Fast code is nice and good, but not at the expense of code readability. I don't care if we lose 5% performance by making things a lot more readable.

I know this is still a work-in-progress, but I wanted to get these comments out while I have the time.

2023-08-09 03:12 UTC, sonicfind commented on YARG.Core/Song/Metadata/SongMetadata.SongPackedRBCON.cs
> +                imgListing = conFile[genPAth + "_keep.png_xbox"];
The index will return a null if the listing doesn't exist at that spot. I'll replace the method without something more descriptive

2023-08-09 04:48 UTC, sonicfind commented on YARG.Core/Song/Preparsers/Midi/MidiDrumPreparser.cs
> +            return true;
Yea, don't worry. The midi preparsers are what I'm planning to go back to once I got everything else in an operational state. It's just that since there's a deadline, there's only so much I could do right away.

2023-08-09 05:35 UTC, TheNathannator commented on YARG.Core/Song/Deserialization/YARGBinaryReader.cs
> +#nullable enable
It's just a tag in the project file, super easy to enable:
```xml
<PropertyGroup>
  ...
  <Nullable>true</Nullable>
  ...
</PropertyGroup>
```

We'll just need to add all of the annotations where needed when we enable it, would be best done as its own set of changes.

2023-08-09 05:35 UTC, TheNathannator commented on YARG.Core/Song/Deserialization/YARGFile.cs
> +        public byte* Data => _data;
> you need to use a pointer and explicit length for nested regions

This is precisely what `Span<T>` and `Memory<T>` are for, you can easily get one from a byte array by using the `AsSpan()`/`AsMemory()` extension methods (or just assigning it directly to a variable of that type), and you can slice them up using the range operator or the `Slice()` method.

2023-08-09 06:00 UTC, sonicfind commented on YARG.Core/Song/Deserialization/YARGFile.cs
> +        public byte* Data => _data;
Except Memory<T> does not have an indexer and must converted to a span on every call you try to use it on. That is *not* a free operation - much like `fixed`.
And I wish I could use a Span<T> as a member variable, but that requires that the readers be `ref struct` which brings a whole other set of issues. SpanSplitter works as it does because every use-case initializes a local variable specifically.

2023-08-09 06:08 UTC, sonicfind commented on YARG.Core/Song/Metadata/PartValues.cs
> +        public sbyte intensity;
It just ensures 1. a sensible range, and 2. that later programmers and/or artists down the road don't have to worry about the prospect of someone trying to make a song with like "hurr durr 2,147,486,647" as the intensity.

0 - 127 as an easy to understand baseline (more for ini songs); full int range for CONs (used in playlist ordering) because they already go higher.

2023-08-09 06:16 UTC, sonicfind commented on YARG.Core/Song/Deserialization/YARGFile.cs
> +        public byte* Data => _data;
That being said, I'll go ahead do Memory<T> for right now

2023-08-09 06:51 UTC, sonicfind commented on YARG.Core/Song/Preparsers/Midi/MidiDrumPreparser.cs
> +            return true;
Did a bunch of constants at least

2023-08-09 07:53 UTC, TheNathannator commented on YARG.Core/Song/Deserialization/YARGFile.cs
> +        public byte* Data => _data;
> and must be converted to a span on every call you try to use it on. That is *not* a free operation - much like `fixed`.

Not as far as I can tell from reading the [code](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Memory.cs#L307); at least in modern .NET, it's just getting the required reference from the array directly using `MemoryMarshal` (which reaches into [internal stuff](https://github.com/dotnet/runtime/blob/main/src/mono/System.Private.CoreLib/src/System/Runtime/InteropServices/MemoryMarshal.Mono.cs#L23) to do its job), and doesn't do any pinning.

After some investigation, it also seems `fixed` doesn't do the same pinning that `GCHandle` does either, the JIT and GC work together to be more efficient about things. [1](https://stackoverflow.com/a/22204244) [2](https://github.com/ralfbiedert/interoptopus/issues/16)

As a final note, `Memory<T>` tracks its data by using an opaque `object` field (no boxing occurs since all types assigned to it are already reference types), alongside index and length fields for where in the data it refers to, there is no copying that happens when you `Slice()`. [1](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Memory.cs#L29-L31)

~~spent far too long researching this 'cause i was curious myself lol~~

2023-08-10 02:48 UTC, sonicfind commented on YARG.Core/Song/Deserialization/YARGChartFileReader.cs
> +        };
While I understand, we should really be actively discouraging the usage of anything other that UTF-8 (although we should handle the Extended ASCII case). Due to how .chart data is formatted, anything other than UTF-8 is just massively bloating filesize. I'd rather have a check on the scanning end that throws an exception (not error) if a UTF-16/32 or other BOM is recognized so that authors don't inadvertently use it.

2023-08-10 02:48 UTC, sonicfind commented on YARG.Core/Song/Deserialization/YARGChartFileReader.cs
> +                throw new Exception($".Cht/.Chart position out of order (previous: {tickPosition})");
ah shit... DON'T LOOK

2023-08-10 03:36 UTC, sonicfind commented on YARG.Core/Song/Deserialization/YARGDTAReader.cs
> +                else if (ch <= 32)
The multiple-multiple levels of indirection on top of a bunch char-type only redundancy checks that char.IsWhitespace brings has always been the sight of a bunch of performance headaches (and how it has to cast to char every time). Like, more than 20%. Not even C++ fixes that shit either.

2023-08-10 19:45 UTC, sonicfind commented on YARG.Core/Song/Deserialization/YARGBinaryReader.cs
> +#nullable enable
I'd rather have this handled as more of a final step for YARG.Core in general, tbh. It's more of a general scope.

2023-08-11 03:29 UTC, merged

2023-08-11 11:33 UTC, TheNathannator commented on YARG.Core/Song/Deserialization/YARGBinaryReader.cs
> +#nullable enable
That's what I was saying lol, this was just a general comment.

2023-08-11 11:53 UTC, TheNathannator commented on YARG.Core/Song/Deserialization/YARGDTAReader.cs
> +                else if (ch <= 32)
interesting, yeah nvm then lol

```
|       Method | character |      Mean |     Error |    StdDev |    Median |
|------------- |---------- |----------:|----------:|----------:|----------:|
| IsWhiteSpace | '\t'      | 0.3537 ns | 0.0094 ns | 0.0088 ns | 0.3570 ns |
|   Is32OrLess | '\t'      | 0.0037 ns | 0.0049 ns | 0.0046 ns | 0.0013 ns |
| IsWhiteSpace | ' '       | 0.3528 ns | 0.0069 ns | 0.0064 ns | 0.3526 ns |
|   Is32OrLess | ' '       | 0.0075 ns | 0.0068 ns | 0.0064 ns | 0.0060 ns |
```