Scan Logging
YARC-Official/YARG.Core pull request #51
Opened 2023-08-14 23:14 UTC by sonicfind

2023-08-14 23:33 UTC, TheNathannator requested changes

2023-08-14 23:33 UTC, TheNathannator commented on YARG.Core/Song/Cache/CacheHandler.cs
> +        public readonly List<string> logs = new();
Any reason you're collecting log messages like this instead of using `YargTrace`'s debug logging methods directly?

This gets rid of the relationship between the message and when it actually happened, and if any errors get logged before these messages do, it will be impossible to correlate the error and this logging together.

`YargTrace` also has `Debug` variants of the logging methods that are only included in debug builds, which verbose/debug logging like this should preferably use (at least for now).

2023-08-14 23:33 UTC, TheNathannator commented on YARG.Core/Song/Cache/CacheHandler.cs
> +                        writer.WriteLine("Path too long the Windows Filesystem (path limitation can be changed in registry settings)");
Missed a word here lol
```diff
- Path too long the Windows Filesystem (path limitation can be changed in registry settings)
+ Path too long for the Windows Filesystem (path limitation can be changed in registry settings)
                ^
```

2023-08-14 23:34 UTC, sonicfind commented on YARG.Core/Song/Cache/CacheHandler.cs
> +                        writer.WriteLine("Path too long the Windows Filesystem (path limitation can be changed in registry settings)");
fuck

2023-08-14 23:35 UTC, sonicfind commented on YARG.Core/Song/Cache/CacheHandler.cs
> +        public readonly List<string> logs = new();
Does YARGTrace handle multithreading by itself?

2023-08-15 02:59 UTC, TheNathannator commented on YARG.Core/Song/Cache/CacheHandler.cs
> +        public readonly List<string> logs = new();
YargTrace itself doesn't, but both console output and Unity's debug logging are thread safe. The only thing that might need to be synchronized is the list of listeners, but in practice that doesn't really matter since only one listener is ever added lol

2023-08-15 03:10 UTC, TheNathannator approved these changes
Looks good now!

2023-08-15 03:10 UTC, merged